### ISSUE TITLE
CocoaDebug auto launch failed alert, even though [CocoaDebug enable] is set.

### ISSUE THREAD

**Issue by mpetrenco** [CocoaDebug/CocoaDebug#100]
Hey guys! 

I have encountered this weird issue where CocoaDebug pops up the `CocoaDebug auto launch failed alert`, even though `[CocoaDebug enable]` has been manually set.

This issue was spotted on **iOS 12.2,** while on **iOS 13.0** it works fine. _(see screenshot below)_.
Fellback to 1.2.9 for now.

![cocoadebug](https://user-images.githubusercontent.com/53521805/87697544-e212df00-c79a-11ea-96a8-1e46ce1e4e2c.png)

Let me know if I can be of any help.
Thanks!

**Comment by CocoaDebug** [comment]
Thanks for your feedback. I will check in soon.

**Comment by mpetrenco** [comment]
Tested and works as expected.
Thanks, @CocoaDebug!
