### ISSUE TITLE
better guidance for conditionally including framework - script suggestion

### ISSUE THREAD

**Issue by 8secz-johndpope** [CocoaDebug/CocoaDebug#101]
UPDATE/ got it all working

some suggestions -  point users to this link
https://raw.githubusercontent.com/CocoaDebug/CocoaDebug/master/CocoaDebug/copy_and_codesign.sh

Save to a Build-Phases folder 
      chmod +x copy_and_codesign.sh 
to allow it to run
 
<img width="1570" alt="Screen Shot 2020-07-23 at 10 39 00 pm" src="https://user-images.githubusercontent.com/50567111/88287211-561e2b80-cd35-11ea-84f1-9b492bd6d03b.png">

include in the run script
$SRCROOT/Build-Phases/cocoadebug_copy_and_codesign.sh

the actual framework can be spat out using cocoa pods by temporarily adding cocoa pods
then  just grab it from DerivedData
~/Library/Developer/Xcode/DerivedData

NOTE - it would be best if this was included in official releases on this site.

**Comment by 8secz-johndpope** [comment]
actually - it seems like this is not possible with cocoapods? Is that right?

I read this - 
https://github.com/CocoaDebug/CocoaDebug/wiki/Integration-Guide

It doesn't seem so simple without adding in a separate app store target.

**Comment by 8secz-johndpope** [comment]
<img width="1379" alt="Screen Shot 2020-07-23 at 10 12 42 pm" src="https://user-images.githubusercontent.com/50567111/88285162-f83c1480-cd31-11ea-9a79-ef661c124a4f.png">


**INPUT**
$(SRCROOT)/CocoaDebug.framework

**Output files**
 ${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/CocoaDebug.framework

**Comment by 8secz-johndpope** [comment]
it the webpage out of date above? can cocoapods do this just by this
 pod 'CocoaDebug', :configurations => ['Debug']

**Comment by CocoaDebug** [comment]
> pod 'CocoaDebug', :configurations => ['Debug']

Yes, Sure.

**Comment by CocoaDebug** [comment]
> NOTE - it would be best if this was included in official releases on this site.

I will fix this soon, thanks~

**Comment by bogdancochioras** [comment]
@8secz-johndpope Any idea how the script can be updated for xcframework?

**Comment by 8secz-johndpope** [comment]
not sure - I abandoned this approach and just use the vanilla 
`pod 'CocoaDebug', :configurations => ['Debug']`
