### ISSUE TITLE
Carthage Only Partially Builds

### ISSUE THREAD

**Issue by Mozahler** [CocoaDebug/CocoaDebug#102]
Getting:
/usr/bin/xcrun xcodebuild -project /Users/Alex/Development/Carthage/CocoaDebug/Carthage/Checkouts/DotzuX/Example_Objc.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'Example_Objc.xcodeproj' from folder '/Users/Alex/Development/Carthage/CocoaDebug/Carthage/Checkouts/DotzuX'.
	Reason: Project /Users/Alex/Development/Carthage/CocoaDebug/Carthage/Checkouts/DotzuX/Example_Objc.xcodeproj cannot be opened because it is missing its project.pbxproj file.

I don't need it, so I didn't look into it.
Just wanted to give you a heads up.

**Comment by CocoaDebug** [comment]
Fixed. Please updated to the latest version.
