### ISSUE TITLE
UI API called on a background thread

### ISSUE THREAD

**Issue by Ptbaileys** [CocoaDebug/CocoaDebug#103]
version 1.4.0

Main Thread Checker: **UI API called on a background thread**: -[UILabel setAttributedText:]
PID: 1319, TID: 480088, Thread name: (none), Queue name: com.mindsnacks.msweaktimer.0x282c285a0, QoS: 0
Backtrace:
4   CocoaDebug                          0x00000001070ed98c -[_DebugConsoleLabel updateLabelWith:value:] + 228
5   CocoaDebug                          0x00000001071ac278 $s10CocoaDebug6BubbleC5frameACSo6CGRectV_tcfcySfcfU_ + 372
6   CocoaDebug                          0x00000001071ac2d8 $sSfIegy_SfIeyBy_TR + 64
7   CocoaDebug                          0x00000001070ef488 -[_DebugMonitor updateValue] + 172
8   CocoaDebug                          0x0000000107184110 -[_WeakTimer timerFired] + 148
9   CocoaDebug                          0x0000000107183ef8 __22-[_WeakTimer schedule]_block_invoke + 60
10  libdispatch.dylib                   0x000000010ddff4d8 _dispatch_client_callout + 20
11  libdispatch.dylib                   0x000000010de02320 _dispatch_continuation_pop + 572
12  libdispatch.dylib                   0x000000010de16224 _dispatch_source_invoke + 1332
13  libdispatch.dylib                   0x000000010de06a54 _dispatch_lane_serial_drain + 260
14  libdispatch.dylib                   0x000000010de07868 _dispatch_lane_invoke + 492
15  libdispatch.dylib                   0x000000010de02150 _dispatch_continuation_pop + 108
16  libdispatch.dylib                   0x000000010de01704 _dispatch_async_redirect_invoke + 684
17  libdispatch.dylib                   0x000000010de11850 _dispatch_root_queue_drain + 356
18  libdispatch.dylib                   0x000000010de121b8 _dispatch_worker_thread2 + 140
19  libsystem_pthread.dylib             0x0000000196b116dc _pthread_wqthread + 216
20  libsystem_pthread.dylib             0x0000000196b179c8 start_wqthread + 8

PID: 1319, TID: 480088, Thread name: (none), Queue name: com.mindsnacks.msweaktimer.0x282c285a0, QoS: 0
Backtrace:
4   CocoaDebug                          0x00000001070ed98c -[_DebugConsoleLabel updateLabelWith:value:] + 228
5   CocoaDebug                          0x00000001071ac278 $s10CocoaDebug6BubbleC5frameACSo6CGRectV_tcfcySfcfU_ + 372
6   CocoaDebug                          0x00000001071ac2d8 $sSfIegy_SfIeyBy_TR + 64
7   CocoaDebug                          0x00000001070ef488 -[_DebugMonitor updateValue] + 172
8   CocoaDebug                          0x0000000107184110 -[_WeakTimer timerFired] + 148
9   CocoaDebug                          0x0000000107183ef8 __22-[_WeakTimer schedule]_block_invoke + 60
10  libdispatch.dylib                   0x000000010ddff4d8 _dispatch_client_callout + 20
11  libdispatch.dylib                   0x000000010de02320 _dispatch_continuation_pop + 572
12  libdispatch.dylib                   0x000000010de16224 _dispatch_source_invoke + 1332
13  libdispatch.dylib                   0x000000010de06a54 _dispatch_lane_serial_drain + 260
14  libdispatch.dylib                   0x000000010de07868 _dispatch_lane_invoke + 492
15  libdispatch.dylib                   0x000000010de02150 _dispatch_continuation_pop + 108
16  libdispatch.dylib                   0x000000010de01704 _dispatch_async_redirect_invoke + 684
17  libdispatch.dylib                   0x000000010de11850 _dispatch_root_queue_drain + 356
18  libdispatch.dylib                   0x000000010de121b8 _dispatch_worker_thread2 + 140
19  libsystem_pthread.dylib             0x0000000196b116dc _pthread_wqthread + 216
20  libsystem_pthread.dylib             0x0000000196b179c8 start_wqthread + 8

**Comment by CocoaDebug** [comment]
Fixed. Please updated to the latest version.
