### ISSUE TITLE
FBRetainCycleDetector error in private library

### ISSUE THREAD

**Issue by FunnyFzl** [CocoaDebug/CocoaDebug#104]
<img width="1288" alt="截屏2020-08-30 下午10 30 53" src="https://user-images.githubusercontent.com/15104149/91661777-b3fe1a00-eb10-11ea-99ad-43a92c797361.png">

**Comment by FunnyFzl** [comment]
过程是，想把CocoaDebug 制作成私有库，在制作私有库的时候，已经把FBRetainCycleDetector 传到私有源，然后针对CocoaDebug做pod lib lint的时候，遇到了下面的报错，一直过不了，希望能帮忙解答一下应该如何处理？
 - ERROR | [iOS] xcodebuild:  FBRetainCycleDetector/FBRetainCycleDetector/Filtering/FBStandardGraphEdgeFilters.mm:25:10: error: returning block that lives on the local stack
    - ERROR | [iOS] xcodebuild:  FBRetainCycleDetector/FBRetainCycleDetector/Filtering/FBStandardGraphEdgeFilters.mm:40:10: error: returning block that lives on the local stack

**Comment by CocoaDebug** [comment]
This .m file not using MRC, please use ARC.

**Comment by FunnyFzl** [comment]
1、 I clone FBRetainCycleDetector, change source, make it to Private libraries(becuse CocoaDebug depend it)
2、I clone CocoaDebug，, change source, make it to Private libraries，when “pod lib lint”，There are a few mistakes，Tip me：
ERROR | [iOS] xcodebuild: FBRetainCycleDetector/FBRetainCycleDetector/Filtering/FBStandardGraphEdgeFilters.mm:25:10: error: returning block that lives on the local stack
ERROR | [iOS] xcodebuild: FBRetainCycleDetector/FBRetainCycleDetector/Filtering/FBStandardGraphEdgeFilters.mm:40:10: error: returning block that lives on the local stack

I haven't changed anything，just  clone、change source、pod lib lint
Please advise how to deal with this error

**Comment by 8secz-johndpope** [comment]
I'm seeing this crash here - is it possible to disable FBRetainCycleDetector without removing cocoadebug completely?
<img width="1524" alt="Screen Shot 2020-09-17 at 5 36 47 pm" src="https://user-images.githubusercontent.com/50567111/93435188-66edb680-f90c-11ea-8507-97ec306fa413.png">

**Comment by hdNguyenPTR** [comment]
It's happening on newer phones / iphone 11 - older phones is fine. seems like it's threading issue.

**Comment by CocoaDebug** [comment]
you can just remove `FBRetainCycleDetector`

**Comment by pongsakorn-onsri** [comment]
Any news? I found this issue today and don't know how to remove just `FBRetainCycleDetector`. So I need to remove this pod to prevent crash.

**Comment by 8secz-johndpope** [comment]
Had to remove entire pod too.

**Comment by CocoaDebug** [comment]
Next version will remove FBRetainCycleDetector

**Comment by CocoaDebug** [comment]
Please update to the latest version

**Comment by zhaozzq** [comment]
`FBRetainCycleDetector` still there

**Comment by CocoaDebug** [comment]
> `FBRetainCycleDetector` still there

Will it still crash?

**Comment by CocoaDebug** [comment]
version 1.5.5 has removed `FBRetainCycleDetector ` now.
