### ISSUE TITLE
vers. 1.6.6

### ISSUE THREAD

**Issue by Ptbaileys** [CocoaDebug/CocoaDebug#129]
![Schermata 2021-07-23 alle 08 57 08](https://user-images.githubusercontent.com/5583713/126747756-46290415-1bae-40d0-ad3b-ec1de5b6aede.png)

**Comment by CocoaDebug** [comment]
What is your CocoaPods version?

**Comment by Ptbaileys** [comment]
1.10.1

**Comment by CocoaDebug** [comment]
Please update to version [1.6.7] 

- remove Protobuf support

**Comment by Ptbaileys** [comment]
Ok

**Comment by CocoaDebug** [comment]
YES

**Comment by Ptbaileys** [comment]
![Schermata 2021-07-23 alle 09 27 33](https://user-images.githubusercontent.com/5583713/126750164-28a1c8fb-3564-4f66-93b2-7aa941c1aa6c.png)

**Comment by CocoaDebug** [comment]
pod install --repo-update

**Comment by Ptbaileys** [comment]
Great job! Thank you very much for the commitment to CocoaDebug
