### ISSUE TITLE
crash in iOS15 beta5

### ISSUE THREAD

**Issue by hubfresher** [CocoaDebug/CocoaDebug#131]
I use  CocoaDebug via cocoapods, when open APP second time, it crashes.please check it

**Comment by CocoaDebug** [comment]
Can you provide more crash information?

**Comment by hubfresher** [comment]
> Can you provide more crash information?
as follows:
 
![Uploading image.png…]()

**Comment by Crazysiri** [comment]
hi, you could use this fixed by haolianfu.
https://github.com/facebook/fishhook/pull/87
https://github.com/haolianfu/fishhook/tree/perfect_fix_crash_on_iOS15
I've tried it on iPhoneX iPhone8 iPhone6s with iOS15, it's perfectly fixed.

**Comment by hubfresher** [comment]
> hi, you could use this fixed by haolianfu.
> [facebook/fishhook#87](https://github.com/facebook/fishhook/pull/87)
> https://github.com/haolianfu/fishhook/tree/perfect_fix_crash_on_iOS15
> I've tried it on iPhoneX iPhone8 iPhone6s with iOS15, it's perfectly fixed.

thx

**Comment by CocoaDebug** [comment]
> hi, you could use this fixed by haolianfu.
> [facebook/fishhook#87](https://github.com/facebook/fishhook/pull/87)
> https://github.com/haolianfu/fishhook/tree/perfect_fix_crash_on_iOS15
> I've tried it on iPhoneX iPhone8 iPhone6s with iOS15, it's perfectly fixed.

@Crazysiri  Great job! You can commit PR. 😄  thx.

**Comment by Creolophus** [comment]
Could you update to fix this issue?

**Comment by CocoaDebug** [comment]
CocoaDebug (1.7.2) successfully published.
