### ISSUE TITLE
Cocoadebug is missing a background color

### ISSUE THREAD

**Issue by philosopherdog** [CocoaDebug/CocoaDebug#140]
I'm seeing the bottom controllers tabbar and navbar when I launch CocoaDebug. I can fix this easily by providing a background color to CocoaDebug. Adding a background color to `vc.view` line 66 of `CocoaDebugViewController` fixes the problem. I'm not sure why I seem to be the only one seeing this. Perhaps my app is using the window in ways most other apps aren't. I'm happy to do a PR and push up the change. Let me know.

![Screenshot of Simulator](https://user-images.githubusercontent.com/530718/151880241-a36cee50-0ddf-41d3-8333-11e38ba40f10.png)
.

**Comment by philosopherdog** [comment]
Does this mean this project is dead? I'm currently on a fork that fixes this issue. Feel free to check it out. https://github.com/philosopherdog/CocoaDebug .

**Comment by asanli-tomdigital** [comment]
I have the same issue.

**Comment by philosopherdog** [comment]
> I have the same issue.

I have a fork that fixes this. If they were taking prs I would make one.

**Comment by asanli-tomdigital** [comment]
yep thanks I started using your fork. idk what's with them.

**Comment by philosopherdog** [comment]
Ok this is now merged. Thanx @CocoaDebug
