### ISSUE TITLE
Latest Build Breaks Settings!

### ISSUE THREAD

**Issue by philosopherdog** [CocoaDebug/CocoaDebug#156]
`4196a173faf36b40857509e84a67748ee7337ffa` removes the settings functionality. I've done a PR to partially fix this. Mean while feel free to point to my fork `https://github.com/philosopherdog/CocoaDebug/tree/settings-fix` which includes the swift5 updates. @CocoaDebug Actually there's a lot of random stuff just being removed without documenting why. Eg. `enableLogMonitoring` no longer works! So I wouldn't use 175 personally. I recommend just pointing to `https://github.com/philosopherdog/CocoaDebug/tree/swift5` as it has all the changes from 175 but none of the breaking stuff.

**Comment by CocoaDebug** [comment]
Thanks. I just want to remove some cumbersome function. Make CocoaDebug simple.

**Comment by CocoaDebug** [comment]
`enableLogMonitoring` is not needed, You can just enable/disable Network/Logs Monitoring on CocoaDebug panel with switch button.

**Comment by CocoaDebug** [comment]
I have revert and published a new version. Thanks.
