### ISSUE TITLE
UINavigationBarAppearance is shared among the application

### ISSUE THREAD

**Issue by lisemyon** [CocoaDebug/CocoaDebug#158]
Hello.

I have an application where UINavigationBarAppearance is already defined. Starting with 1.7.6 version I have a conflict between CocoaDebug's navigation bar style and mine. Is it possible to change navigation color without setting UINavigationBar.appearance().standardAppearance and UINavigationBar.appearance().scrollEdgeAppearance as it may impact general app's appearances ?

**Comment by CocoaDebug** [comment]
Yeah, it's new added codes in 1.7.6 version. I will fix soon. thanks

**Comment by CocoaDebug** [comment]
1.7.7 fixed. @lisemyon
