### ISSUE TITLE
NetworkDetailViewController tableview low performance on long json response

### ISSUE THREAD

**Issue by KimTaeHyeong17** [CocoaDebug/CocoaDebug#165]
### as-is
when loading long json response in NetworkDetailViewController, screen become laggy

### to-be
improve long text loading performance or just show preview json in NetworkDetailViewController and when user tap NetworkDetailCell, show full text in another fullScreen

can I work on this?

**Comment by CocoaDebug** [comment]
Sure! Thanks.
