### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by gwpp** [CocoaDebug/CocoaDebug#28]
这种小工具其实可以不让业务方初始化的，自己监听一下didFinishLaunch通知，在通知回调里初始化就好了，不用让调用者来区分DEBUG、RELEASE还或者是其他环境，因为在Podfile里就可以限制

**Comment by CocoaDebug** [comment]
- 如果需要自定义一些CocoaDebug初始化参数，还是需要在`didFinishLaunch `写自己的代码
 - 目前CocoaDebug对外的方法`enable()`和`disable()`可以更加灵活的开启和关闭debug功能

所以，在`didFinishLaunch `业务方初始化还是更加灵活，毕竟每个人的需求可能都不太一样，其实也就是一行代码的事。
