### ISSUE TITLE
what's the difference between CocoaDebug and FLEX

### ISSUE THREAD

**Issue by nyz110** [CocoaDebug/CocoaDebug#29]
As the title

**Comment by haoht** [comment]
There are many difference. You can check [README](https://github.com/CocoaDebug/CocoaDebug/blob/master/README) for more information. Thanks.

**Comment by CocoaDebug** [comment]
There are many difference. You can check [README](https://github.com/CocoaDebug/CocoaDebug/blob/master/README.md) for more information. Thanks.
