### ISSUE TITLE
使用MLeaksFinder会检测到Memory Leak

### ISSUE THREAD

**Issue by hell03W** [CocoaDebug/CocoaDebug#30]
**问题**:项目中同时集成MLeaksFinder, 打开CocoaDebug的"SandBox"页面, 点击左上角关闭, MLeaksFinder报Memory Leak.

![](http://7xv47b.com1.z0.glb.clouddn.com/18-8-5/70860150.jpg)

**原因**:经检查, 关闭后, SandboxViewController控制器仍然被Sandbox的单例对象持有, 导致无法被正常销毁.

**解决**:Sandbox的homeDirectoryNavigationController方法每次返回新的UINavigationController.

```
- (UINavigationController *)homeDirectoryNavigationController {
    SandboxViewController *sandboxViewController = [[SandboxViewController alloc] init];
    sandboxViewController.homeDirectory = YES;
    sandboxViewController.fileInfo = [[MLBFileInfo alloc] initWithFileURL:self.homeFileURL];
    UINavigationController *navi = [[UINavigationController alloc] initWithRootViewController:sandboxViewController];
    return navi;
}
```

**Comment by CocoaDebug** [comment]
新版本已经发布，已经解决此bug，请更新。
谢谢~
