### ISSUE TITLE
日志打印的问题

### ISSUE THREAD

**Issue by sujiewen** [CocoaDebug/CocoaDebug#33]
我的引用代码：

    #ifdef DEBUG
    #define LRString [NSString stringWithFormat:@"%s", __FILE__].lastPathComponent
    #define NSLog(fmt, ...) [CocoaDebug objcLog:[[NSString stringWithUTF8String:__FILE__] lastPathComponent] :NSStringFromSelector(_cmd) :__LINE__ :(fmt, ##__VA_ARGS__) :[UIColor whiteColor]]
    #else
    static const DDLogLevel ddLogLevel = DDLogLevelWarning;
    #if defined(OM_BETA) || defined(OM_TEST)
    #define NSLog(fmt, ...) [CocoaDebug objcLog:[[NSString stringWithUTF8String:__FILE__] lastPathComponent] :NSStringFromSelector(_cmd) :__LINE__ :(fmt, ##__VA_ARGS__) :[UIColor whiteColor]]
    #else
    #define NSLog DDLogError
    #endif

    #endif

    #endif

报错：
    Controller/AddTimeApplyController.m:446:9: error: sending 'CGFloat' (aka 'double') to parameter of incompatible type 'id _Nonnull'
        NSLog(@"%f",progress);

//////////////////////////////////////////////////////////////////

NSLog(""),里面必须是NSString?

**Comment by CocoaDebug** [comment]
建议你参考下我的Objective-C的示例项目，没有出现这种情况。应该是NSLog宏定义的问题。

**Comment by sujiewen** [comment]
demo也有这个问题

**Comment by CocoaDebug** [comment]
好的，我check一下

**Comment by CocoaDebug** [comment]
确实Objective-C的demo也有此问题，swift的demo暂无问题。

暂时没有好的解决方案，欢迎大家提PR

**Comment by CocoaDebug** [comment]
🚀 CocoaDebug (0.2.2) successfully published.
Please update to last version. Thanks!
