### ISSUE TITLE
接口返回很多数据时，response不显示

### ISSUE THREAD

**Issue by ZSMHup** [CocoaDebug/CocoaDebug#36]
![c8902f73ec8db9aeb302f04b25acb1e0](https://user-images.githubusercontent.com/20026815/45140237-ba3cb280-b1e4-11e8-8717-134d7771b9cf.png)

**Comment by ZSMHup** [comment]
控制台会打印 [<__UITextTiledLayer: 0x6040002c77e0> display]: Ignoring bogus layer size (994.000000, 103734.000000), contentsScale 2.000000, backing store size (1988.000000, 207468.000000)

**Comment by CocoaDebug** [comment]
response是json数据吗？ 考虑到性能，response有最大显示行数限制

**Comment by CocoaDebug** [comment]
可否在该界面摇一摇，将信息发到我的邮箱。周末我改进一下  
CocoaDebug@gmail.com

**Comment by ZSMHup** [comment]
你好，已发送，请查收一下

**Comment by CocoaDebug** [comment]
新版本已经发布，解决：
- response不显示 (cell的最大可显示高度为5522，json数据过大显示不全时，可以点击标题`RESPONSE`的最右边空白区域，可跳转到新界面显示全部json)

未解决：
- 点击列表进入详情反应很慢，隔了好几秒才会跳转 (因为response data的数据过大，转换成string时会卡顿几秒，如果有解决方案欢迎提PR) 

@ZSMHup
