### ISSUE TITLE
加载图片时会崩溃

### ISSUE THREAD

**Issue by uncleRX** [CocoaDebug/CocoaDebug#37]
![1536574310334](https://user-images.githubusercontent.com/16251490/45291547-1412e480-b525-11e8-9c50-cfb3fff20ea5.jpg)

**Comment by uncleRX** [comment]
发生在 列表cell 加载网络图片的时候

**Comment by CocoaDebug** [comment]
截图看不太清楚，有完整的堆栈信息吗？确定是CocoaDebug库引起的吗？

**Comment by CocoaDebug** [comment]
你用的cocoadebug版本是？ 你发的截图确实看不出问题所在。能提供更详细的日志吗？ 

欢迎提PR

**Comment by uncleRX** [comment]
版本是0.11
我也只能看到类似于这种的堆栈,报错信息看不出来
![1536894003786](https://user-images.githubusercontent.com/16251490/45527290-61d16a80-b80d-11e8-91e5-463b3c970689.jpg)

**Comment by uncleRX** [comment]
![image](https://user-images.githubusercontent.com/16251490/46054247-0a21f000-c179-11e8-930b-f579d9fc24f5.png)
全局断点,跟异常断点不会进.  这个错误是经常出现的

**Comment by CocoaDebug** [comment]
你好，请问bug仍然存在吗？ 

`EXC_BAD_ACCESS`是访问了已经释放了的对象导致的，使用Zombie和Address Sanitizer可以准确定位问题，你可以这样设置，谢谢!

![snip20181030_2](https://user-images.githubusercontent.com/6781027/47709401-211d9b80-dc6b-11e8-9987-e727d240fd5f.png)

**Comment by CocoaDebug** [comment]
🚀  CocoaDebug (0.2.2) successfully published.
Please update to last version. Thanks!

**Comment by haoht** [comment]
Good
