### ISSUE TITLE
 malloc: *** error for object: pointer being freed was not allocated

### ISSUE THREAD

**Issue by menesh2** [CocoaDebug/CocoaDebug#40]
Hi,
i keep getting this exception :  "malloc: *** error for object: pointer being freed was not allocated"
when i am making this call:  `swiftHandleLog(file, function, line, message, color)`
I'm getting this exception almost every time but if i mark this line (and just prints the same text) everything goes well an the app works just fine.
can you tell what may cause this problem?
am i doing something wrong?

**edit:**
the crash happens on LogHelper.swift at line 35: `LogStoreManager.shared.addLog(newLog)`

**Comment by menesh2** [comment]
sorry, but can you be more detailed?
what do you mean by "authored the thread"?
how do i solve it?

‫בתאריך יום ב׳, 22 באוק׳ 2018 ב-9:30 מאת ‪CocoaDebug‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by CocoaDebug** [comment]
I will fix soon. My macbook has broken now. Sorry

**Comment by menesh2** [comment]
Great! Thank you

בתאריך יום ו׳, 26 באוק׳ 2018, 11:26, מאת CocoaDebug ‏<
notifications@github.com>:

**Comment by CocoaDebug** [comment]
![snip20181030_2](https://user-images.githubusercontent.com/6781027/47709401-211d9b80-dc6b-11e8-9987-e727d240fd5f.png)

Try this in Xcode if this crash happen again, thanks

**Comment by CocoaDebug** [comment]
🚀  CocoaDebug (0.2.2) successfully published.
Please update to last version. Thanks!

**Comment by haoht** [comment]
Good
