### ISSUE TITLE
Enhance CustomProtocol

### ISSUE THREAD

**Issue by codwam** [CocoaDebug/CocoaDebug#45]
Some request need user & password get 401?

**Comment by CocoaDebug** [comment]
Do you have any screenshots ?

**Comment by codwam** [comment]
Yes, but it's internal url.
I find the root case which is not implement some delegates method.
`- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential *))completionHandler
`

It can not call my custom `sessionDidReceiveChallengeWithCompletion` and `taskDidReceiveChallengeWithCompletion` implementation while using Moya third-party framework?

**Comment by CocoaDebug** [comment]
Yes, you can find my source codes in `CustomProtocol.m`
Welcome to PR(pull request).

**Comment by CocoaDebug** [comment]
Please update `CocoaDebug` to last version. Thanks!

**Comment by codwam** [comment]
Nope. Apple's `CustomHTTPProtocol` not help at all.
Using swizzle instead of NSURLProtocol?
May be try belows:
[https://github.com/Flipboard/FLEX/tree/master/Classes/Network](https://github.com/Flipboard/FLEX/tree/master/Classes/Network)
