### ISSUE TITLE
CustomProtocol has memory leaks

### ISSUE THREAD

**Issue by GrayLand119** [CocoaDebug/CocoaDebug#49]
![image](https://user-images.githubusercontent.com/11648047/50870374-b9b26380-13f2-11e9-92f1-b516af9cac43.png)

There is my Leaks's Logs with my app running in 30s:

    416 Bytes    1.3%	4	 	+[UIWebView(BlocksKit) load]
  11.56 KB      39.3%	7	 	-[CustomProtocol URLSession:dataTask:didReceiveData:]
  15.97 KB      54.3%	123	 	-[CustomProtocol startLoading]

**Comment by CocoaDebug** [comment]
Please update to last version.

**Comment by GrayLand119** [comment]
Fixed in latest version.
