### ISSUE TITLE
Status bar color 颜色被修改为黑色

### ISSUE THREAD

**Issue by jihongboo** [CocoaDebug/CocoaDebug#50]
CocoaDebug设置为enable后，App 的Status bar color就会被设置成黑色（原来是白色）。

**Comment by CocoaDebug** [comment]
CocoaDebug是最新版本吗？

**Comment by jihongboo** [comment]
是的，测试后发现，通过摇动隐藏悬浮球后，Status bar color恢复正常，显示悬浮球后又影响了Status bar color。那么能否让CocoaDebug enable后，先默认隐藏悬浮球，这样也就默认不影响App了。

**Comment by jihongboo** [comment]
原来CocoaDebug是会记住上次是否隐藏这个属性的，那应该没问题了。

**Comment by CocoaDebug** [comment]
嗯，可以关闭issue了

**Comment by CocoaDebug** [comment]
导致的原因是：悬浮球显示后，也会有一个透明的UIWindow显示，默认的`StatusBar`样式为`default`。悬浮球隐藏后，透明的UIWindow也隐藏了。
