### ISSUE TITLE
WKWebView goback not works

### ISSUE THREAD

**Issue by FunnyFzl** [CocoaDebug/CocoaDebug#58]
导入CocoaDebug 之后，WKWebView 的goback 不起作用

**Comment by CocoaDebug** [comment]
![屏幕快照 2019-04-02 上午11 45 56](https://user-images.githubusercontent.com/6781027/55375021-24c88d80-553d-11e9-8f97-a5453b8619ee.png)
可以禁用掉H5日志监控，再试试看

**Comment by wmh8638** [comment]
排查bug排查了两天 终于。。。。。令人窒息的操作

**Comment by CocoaDebug** [comment]
[捂脸]
