### ISSUE TITLE
WKWebView not call dealloc/deinit

### ISSUE THREAD

**Issue by jihongboo** [CocoaDebug/CocoaDebug#59]
如题，导入CocoaDebug 之后，项目中所有用到的WKWebView都无法释放。

**Comment by CocoaDebug** [comment]
![屏幕快照 2019-04-02 上午11 45 56](https://user-images.githubusercontent.com/6781027/55375021-24c88d80-553d-11e9-8f97-a5453b8619ee.png)
可以禁用掉H5日志监控，再试试看
