### ISSUE TITLE
[_NSActivityAssertion stopLoading]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by xiaoGoO** [CocoaDebug/CocoaDebug#70]
name:NSInvalidArgumentException
reason:
-[_NSActivityAssertion stopLoading]: unrecognized selector sent to instance 0x600000160780
callStackSymbols:
(null)libc++abi.dylib: terminating with uncaught exception of type NSException

Xcode 10.3

**Comment by CocoaDebug** [comment]
Please import `CocoaDebug` via [Carthage](https://www.raywenderlich.com/416-carthage-tutorial-getting-started).

**Comment by xiaoGoO** [comment]
But my Jenkins configuration also uses Pods. If it has been replaced, the changes are relatively large. Is there any other way?
--------------------------------------
但是我的Jenkins配置也是使用Pods 如果过更换的话改动比较大，有没有其他办法？

**Comment by CocoaDebug** [comment]
`CocoaDebug ` can be imported manually using Carthage. just import the `.framework`

**Comment by xiaoGoO** [comment]
@CocoaDebug Thank you, already solved with Carthage
-----------------------------------------------
 @CocoaDebug 谢谢， 已经使用Carthage解决了
