### ISSUE TITLE
`Example_Objc` build failed because `Build input files cannot be found`

### ISSUE THREAD

**Issue by allenlinli** [CocoaDebug/CocoaDebug#71]
# Reproduce Steps
1. Download the source code from master (`31eed1c7`)
2. Open `Example_Objc.xcodeproj` and build it on Xcode
3. Error shows
The error message:
```
:-1: Build input files cannot be found: '/Users/allenlinli/Desktop/CocoaDebug-master/Sources/Logs/LogHelper.swift', '/Users/allenlinli/Desktop/CocoaDebug-master/Sources/App/CrashModel.swift', '/Users/allenlinli/Desktop/CocoaDebug-master/Sources/Window/WindowHelper.swift'
```

# Environment
Xcode Version 10.3 (10G8)
macOS Mojave 10.14.4 (18E226)
simulator iPhoineXR iOS 10.4
device iPhone 6 iOS 12.4

Thanks.

**Comment by CocoaDebug** [comment]
Has been resolved now.

**Comment by allenlinli** [comment]
Works as expected. Thanks.
