### ISSUE TITLE
AppStore Review

### ISSUE THREAD

**Issue by ZJF-Coder** [CocoaDebug/CocoaDebug#74]
I see in the introduction that there is a reference to private Api, can the project refer to this when it hits the appstore?

**Comment by CocoaDebug** [comment]
You can remove the private APIs.

**Comment by ZJF-Coder** [comment]
Thank you very much

**Comment by ZJF-Coder** [comment]
Why I deleted the global UIDebuggingInformationOverlay, but long will appear UIDebuggingInformationOverlay view on time? Did I remove it insufficiently?

**Comment by CocoaDebug** [comment]
The private APIs has been removed.
