### ISSUE TITLE
Hover Button problem

### ISSUE THREAD

**Issue by ZJF-Coder** [CocoaDebug/CocoaDebug#75]
Hello, I found that sometimes after running for a period of time, I could not see the hover button. After uninstalling the app, I installed it again and returned to normal

**Comment by CocoaDebug** [comment]
what is the `Hover Button` ?  can you provide some screenshots ?

**Comment by ZJF-Coder** [comment]
In appdelegate, after initializing cocoadebug. enable(), the debug hover button cannot appear in the program. I have also checked the breakpoint that cocoadebug. enable() has finished execution, but the button cannot appear

**Comment by CocoaDebug** [comment]
Try shake iPhone ?

**Comment by ZJF-Coder** [comment]
Thanks~ That solved my problem
