### ISSUE TITLE
Use of deprecated API

### ISSUE THREAD

**Issue by ricardohochman** [CocoaDebug/CocoaDebug#78]
When uploading a new version of my app to Apple, I receive an email warning about deprecated API for UIWebView.

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Could you fix this?

**Comment by CocoaDebug** [comment]
Please do not import `CocoaDebug` in release version.

`
    pod 'CocoaDebug', :configurations => ['Debug']
`

**Comment by ricardohochman** [comment]
I don't use it in release version, but I send a beta version of my app to TestFlight in Debug.

**Comment by mertnesvat** [comment]
Same here, although I added only for the Debug configuration and I'm sending release it still complains.

**Comment by mertnesvat** [comment]
So it seems it's just a warning and does not cause to Appstore Rejection there's a long discussion in the [RxSwift project](https://github.com/ReactiveX/RxSwift/issues/2055) also [here in ionic blog](https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/) mentioned.

> Currently, no, since this is just a warning, not an error. Warnings will not result in App Store rejections. UIWebView APIs are still supported in the upcoming iOS 13 release as well as macOS Catalina but are still going away in future releases.

>

**Comment by ricardohochman** [comment]
@CocoaDebug Apple updated the warning:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from **April 2020**. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by CocoaDebug** [comment]
I see. Thanks

**Comment by ricardohochman** [comment]
@CocoaDebug Reopening this issue. Now Apple blocked my app from uploading to TestFlight because of WKWebView.

> We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload again.
> 
> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by CocoaDebug** [comment]
I will remove UIWebView in next version soon. Thanks.

**Comment by CocoaDebug** [comment]
CocoaDebug (1.2.6) successfully published.
UIWebView and private APIs has been removed.
