### ISSUE TITLE
WKWebView 不应该 removeAllUserScripts

### ISSUE THREAD

**Issue by iblacksun** [CocoaDebug/CocoaDebug#84]
WKWebView load 方法内有 `[configuration.userContentController removeAllUserScripts];`，导致自定义 UserScripts 全部失效了

**Comment by CocoaDebug** [comment]
Thanks. 
If convenient, you can pull a Merge Request.

**Comment by iblacksun** [comment]
@CocoaDebug 请查看 #85

**Comment by iblacksun** [comment]
@CocoaDebug release CocoaPods version please?

**Comment by CocoaDebug** [comment]
CocoaDebug (1.0.3) successfully published.
