### ISSUE TITLE
fps and memory

### ISSUE THREAD

**Issue by bianzhifeng** [CocoaDebug/CocoaDebug#91]
When I use Swift I can't see fps and memory

**Comment by CocoaDebug** [comment]
I removed it. Because it will cause memory leaks.

**Comment by alouanemed** [comment]
I am using the latest version and still can see fps and memory. and yeah you were right there were some leaks with cocodebug.

**Comment by CocoaDebug** [comment]
What's your CocoaDebug version number ?

**Comment by CocoaDebug** [comment]
run `pod update CocoaDebug`

**Comment by CocoaDebug** [comment]
The latest version is 1.2.5
